import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import './globals.css';

import { ubuntu } from '@/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${ubuntu.className} antialiased`}>
                <ThemeProvider attribute={'class'}>{children}</ThemeProvider>
            </body>
        </html>
    );
}
