import {
    RGBAColor,
    ChartFilter,
    GridOrientation,
    SortType,
    AreaChartType,
    GridType,
    AnchorType,
    SORT_NONE,
    GRID_ORIENTATION_HORIZONTAL,
    GRID_TYPE_SOLID,
    FONT_OPTIONS,
    ANCHOR_MIDDLE,
    AREA_CHART_TYPE_LINEAR,
    FontStyleType,
    FONT_STYLES_NORMAL,
} from "@/constants";

const defaultAreaChartConfig = {
    background_color: { r: 255, g: 255, b: 255, a: 1 } as RGBAColor,
    text_color: { r: 0, g: 0, b: 0, a: 1 } as RGBAColor,
    tooltip_enabled: true,
    label: "area chart",
    label_enabled: true,
    label_size: 12,
    label_anchor: ANCHOR_MIDDLE as AnchorType,
    label_color: { r: 0, g: 0, b: 0, a: 1 } as RGBAColor,
    label_font_family: FONT_OPTIONS[0],
    label_font_style: FONT_STYLES_NORMAL as FontStyleType,
    legend_enabled: true,
    border_enabled: false,
    color_palette: [] as RGBAColor[],
    x_axis_field: "",
    y_axis_field: "",
    x_sort_order: SORT_NONE as SortType,
    y_sort_order: SORT_NONE as SortType,
    omit_zero_values_enabled: false,
    cumulative_enabled: false,
    filters: [] as ChartFilter[],
    grid_color: { r: 200, g: 200, b: 200, a: 1 } as RGBAColor,
    grid_orientation: GRID_ORIENTATION_HORIZONTAL as GridOrientation,
    grid_type: GRID_TYPE_SOLID as GridType,
    grid_width: 1,
    y_axis_enabled: true,
    x_axis_enabled: true,
    stacked_enabled: false,
    area_style: AREA_CHART_TYPE_LINEAR as AreaChartType,
    stroke_width: 2,
    fill_opacity: 0.5,
    is_area_chart: true,
    margin_top: 20,
    margin_bottom: 20,
    margin_left: 20,
    margin_right: 20,
};

export default defaultAreaChartConfig;
